import { Unbounded } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const UnboundedRegular = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
});


export const metadata = {
  title: "BlockHeader Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${UnboundedRegular.variable}`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}